from .ontoDoIsAProcessor import OntoDoIsAProcessor
from .ontoGoIsAProcessor import OntoGoIsAProcessor
from .ontoHpoIsAProcessor import OntoHpoIsAProcessor
from .ontoUberonIsAProcessor import OntoUberonIsAProcessor
from .ontoGoPartOfProcessor import OntoGoPartOfProcessor
from .ontoUberonPartOfProcessor import OntoUberonPartOfProcessor