from enum import Enum


class EdgeType (Enum):
    IS_A = 0
    HAS_A = 1

    GENE_GENE = 10
    GENE_GO = 11
    GENE_DIS = 12
    GENE_DRUG = 13
    GENE_PHENOTYPE = 14
    GENE_PATHWAY = 15
    GENE_EXPRESSED_ANATOMY = 16
    DIS_DRUG = 17
    DIS_PHENOTYPE = 18
    DRUG_PHENOTYPE = 19
    GENE_OVEREXPRESSED_ANATOMY = 20
    GENE_UNDEREXPRESSED_ANATOMY = 201

    DRUG_ACTIVATION_GENE = 21
    DRUG_BINDING_GENE = 22
    DRUG_CATALYSIS_GENE = 23
    DRUG_EXPRESSION_GENE = 24
    DRUG_INHIBITION_GENE = 25
    DRUG_PREDBIND_GENE = 26
    DRUG_REACTION_GENE = 27
    DRUG_BINDACT_GENE = 28
    DRUG_BINDINH_GENE = 29

    GENE_ACTIVATION_GENE = 31
    GENE_BINDING_GENE = 32
    GENE_CATALYSIS_GENE = 33
    GENE_EXPRESSION_GENE = 34
    GENE_INHIBITION_GENE = 35
    GENE_PTMOD_GENE = 36
    GENE_REACTION_GENE = 37
    GENE_BINDACT_GENE = 38
    GENE_BINDINH_GENE = 39