from .ontoMapDoOmimProcessor import OntoMapDoUmlsProcessor
from .ontoMapDoUmlsProcessor import OntoMapDoUmlsProcessor
from .ontoMapHpoUmlsProcessor import OntoMapHpoUmlsProcessor
from .ontoMapDoAltidProcessor import OntoMapDoAltidProcessor
from .ontoMapGoAltidProcessor import OntoMapGoAltidProcessor
from .ontoMapHpoAltidProcessor import OntoMapHpoAltidProcessor
from .ontoMapUberonAltidProcessor import OntoMapUberonAltidProcessor