from .edgeMetaDisDrug     import EdgeMetaDisDrug
from .edgeMetaGeneGo      import EdgeMetaGeneGo
from .edgeMetaDisPheno    import EdgeMetaDisPheno
from .edgeMetaGenePheno   import EdgeMetaGenePheno
from .edgeMetaGeneDrug    import EdgeMetaGeneDrug
from .edgeMetaGeneAna     import EdgeMetaGeneAna
from .edgeMetaGeneGene    import EdgeMetaGeneGene
from .edgeMetaGeneDis     import EdgeMetaGeneDis
from .edgeMetaGenePath    import EdgeMetaGenePath
from .edgeMetaDrugPheno   import EdgeMetaDrugPheno